owner: finalSddd
repo: status-probe

sites:
  - name: TAG机场
    url: https://tagss.pro
  - name: CoffeeCloud
    url: https://aicoffee.app
  - name: 肥猫云 (FatCat Cloud)
    url: https://inv03.fcweba.cc
  - name: Nexitally 奶昔机场
    url: https://nxonearth.com
  - name: SNTP 守候网络
    url: https://dash15.newsntp.net
  - name: BoostNet
    url: https://999.boostnet1.com
  - name: NiceCloud 耐思云
    url: https://nicecloud.co
  - name: Yue.to 悦通
    url: https://my.yue.to
  - name: 星链机场
    url: https://www.xn--mes995ajya725k.com

status-website:
  baseUrl: /status-probe
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: 机场服务状态监控
  introTitle: "**机场在线状态监控**，实时检测各大机场官网及接口的连通性。"
  introMessage: 本页面每 5 分钟自动测试一次各大机场官网的响应时间及可用性。如果在选购机场时担心跑路或宕机，可以参考本页面的 30 天在线率。
  navbar:
    - title: 监控状态
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
    - title: 机场推荐首页
      href: https://mixc6763-prog.github.io/jichangce
